<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCWEPNN\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCWEPNN/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZCWEPNN.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZCWEPNN\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZCWEPNN\appAppKernelProdContainer([
    'container.build_hash' => 'ZCWEPNN',
    'container.build_id' => '05d88b42',
    'container.build_time' => 1704208029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCWEPNN');
