<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'svWth80OYbHfcg',
	'db_user' => 'svWth80OYbHfcg',
	'db_password' => 'SMkAdhBKdO1Yw2',
	'db_backup_tables' => false,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'Admin Mautic',
	'mailer_from_email' => 'diepminhhieu0805@gmail.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => '3af213e08e5600858e4302ade9ffb4426fb2a7b821887c13c57bce1523563999',
	'site_url' => 'http://minhhieu2k3.click',
);
